runtime: python3106
entrypoint: gunicorn -b

instance_class: F4_1G  # Higher memory instance for TensorFlow models
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  MODEL_TEXT_PATH: "/home/romaric/code/Romaric1209/GAIDI/notebooks/roma_models/baseline_model.keras"
  MODEL_IMG_PATH: "/home/romaric/code/Romaric1209/GAIDI/notebooks/roma_models/baseline_image.keras"

handlers:
- url: /.*
  script: auto
